apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "postgres.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgres.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgres.name" . }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgresql
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "postgres.fullname" . }}
          ports:
            - name: tcp-postgresql
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          resources:
{{- with .Values.resources }}
{{ toYaml . | indent 12 }}
{{- end }}
      volumes:
{{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
