mimir:
  structuredConfig:
    multitenancy_enabled: false
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /tmp/mimir
    compactor:
      data_dir: /tmp/mimir/compactor
nginx:
  enabled: true
