apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.url }}
