apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}
  labels:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
