fullnameOverride: ""
image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent
service:
  port: 5432
credentials:
  username: todo
  password: todo
  database: todo
persistence:
  enabled: false
  size: 2Gi
resources:
  requests:
    cpu: 100m
    memory: 128Mi
