project_id        = "sandbox-project-tc"
region            = "us-central1"
environment       = "preview"
database_tier     = "db-custom-1-3840"
authorized_cidr   = "0.0.0.0/0"
database_user     = "todo"
database_password = "todo-preview"
database_name     = "todo"
