name: E2E
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  workflow_call:

env:
  GCP_PROJECT: example-project
  GCP_REGION: us-central1
  GAR_REPOSITORY: us-central1-docker.pkg.dev/example-project/template-go

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start minikube
        uses: medyagh/setup-minikube@v0.0.15
        with:
          kubernetes-version: v1.28.0
      - name: Skaffold deploy
        uses: hiberbee/github-action-skaffold@v1
        with:
          command: run
          profile: minikube
      - name: Helm integration tests
        run: |
          helm test todo-app -n todo --filter integration --timeout 5m
          helm test todo-app -n todo --filter load --timeout 10m
      - name: Grafana smoke test
        run: kubectl run curl --image=curlimages/curl --rm -i --restart=Never -- curl -sf http://todo-grafana.observability/api/health
