name: SLSA
on:
  push:
    branches: [main]

jobs:
  provenance:
    permissions:
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      upload-assets: true
      build-artifact-path: dist
      build-artifact-name: template-go
      run-slsa-build: true
