name: Test
on:
  pull_request:
  push:
    branches: [main]

env:
  GAR_REPOSITORY: us-central1-docker.pkg.dev/example-project/template-go

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Go test
        run: go test ./...
      - name: Container structure tests
        uses: GoogleContainerTools/container-structure-test-action@v1
        with:
          image: ${GAR_REPOSITORY}/todo-app:latest
          config: structure-test.yaml
  e2e:
    needs: unit
    uses: ./.github/workflows/e2e.yml
